export const arr = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        layout: 'products',
        customFields: {},
    },
];

const i = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        layout: 'products',
        customFields: {},
    },
];

const myCataFlat = [
    {
        id: 8,
        type: 'shop',
        name: 'Коленвал',
        slug: 'kolenval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 7, name: 'Поршневая', slug: 'porshnevaja', lft: 8, rght: 15, tree_id: 2, level: 1, parent: 2 },
        children: [],
    },
    {
        id: 9,
        type: 'shop',
        name: 'Поршни',
        slug: 'porshni',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 7, name: 'Поршневая', slug: 'porshnevaja', lft: 8, rght: 15, tree_id: 2, level: 1, parent: 2 },
        children: [[Object]],
    },
    {
        id: 10,
        type: 'shop',
        name: 'Кольца поршневые',
        slug: 'koltsa-porshnevye',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 9, name: 'Поршни', slug: 'porshni', lft: 11, rght: 14, tree_id: 2, level: 2, parent: 7 },
        children: [],
    },
    {
        id: 27,
        type: 'shop',
        name: 'Распредвал',
        slug: 'raspredval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 6, name: 'Головка', slug: 'fuel-system', lft: 2, rght: 7, tree_id: 2, level: 1, parent: 2 },
        children: [],
    },
    {
        id: 28,
        type: 'shop',
        name: 'Головка в сборе',
        slug: 'golovka-v-sbore',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 6, name: 'Головка', slug: 'fuel-system', lft: 2, rght: 7, tree_id: 2, level: 1, parent: 2 },
        children: [],
    },
    {
        id: 29,
        type: 'shop',
        name: 'Масляный насос',
        slug: 'masljanyj-nasos',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 2, name: 'Двигатель', slug: 'dvigatel', lft: 1, rght: 30, tree_id: 2, level: 0, parent: null },
        children: [],
    },
    {
        id: 31,
        type: 'shop',
        name: 'Радиатор',
        slug: 'radiator',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: { id: 2, name: 'Двигатель', slug: 'dvigatel', lft: 1, rght: 30, tree_id: 2, level: 0, parent: null },
        children: [],
    },
];
