import { IBaseCategory } from '~/interfaces/category';

export const arr = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        layout: 'products',
        customFields: {},
    },
];

const i = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        layout: 'products',
        customFields: {},
    },
];

export const myCataFlat: any = [
    {
        id: 8,
        type: 'shop',
        name: 'Коленвал',
        slug: 'kolenval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
    {
        id: 9,
        type: 'shop',
        name: 'Поршни',
        slug: 'porshni',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [[Object]],
    },
    {
        id: 10,
        type: 'shop',
        name: 'Кольца поршневые',
        slug: 'koltsa-porshnevye',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
    {
        id: 27,
        type: 'shop',
        name: 'Распредвал',
        slug: 'raspredval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
    {
        id: 28,
        type: 'shop',
        name: 'Головка в сборе',
        slug: 'golovka-v-sbore',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
    {
        id: 29,
        type: 'shop',
        name: 'Масляный насос',
        slug: 'masljanyj-nasos',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
    {
        id: 31,
        type: 'shop',
        name: 'Радиатор',
        slug: 'radiator',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',

        children: [],
    },
];

const shopTree = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        children: [],
        layout: 'products',
        customFields: {},
    },
];

const prepared = [
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        layout: 'products',
        customFields: {},
    },
];

export const shopCategoryLst: any = [
    {
        id: 2,
        type: 'shop',
        name: 'Двигатель',
        slug: 'dvigatel',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [
            {
                id: 6,
                name: 'Головка',
                slug: 'fuel-system',
                lft: 2,
                rght: 7,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 7,
                name: 'Поршневая',
                slug: 'porshnevaja',
                lft: 8,
                rght: 15,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 29,
                name: 'Масляный насос',
                slug: 'masljanyj-nasos',
                lft: 16,
                rght: 17,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 30,
                name: 'Генератор',
                slug: 'generator',
                lft: 18,
                rght: 19,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 31,
                name: 'Радиатор',
                slug: 'radiator',
                lft: 20,
                rght: 21,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 32,
                name: 'Вискомуфта',
                slug: 'viskomufta',
                lft: 22,
                rght: 23,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 33,
                name: 'Поддон',
                slug: 'poddon',
                lft: 24,
                rght: 25,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 34,
                name: 'Блок цилиндров',
                slug: 'blok-tsilindrov',
                lft: 26,
                rght: 27,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
            {
                id: 35,
                name: 'Крышка клапанов',
                slug: 'kryshka-klapanov',
                lft: 28,
                rght: 29,
                tree_id: 2,
                level: 1,
                parent: 2,
            },
        ],
    },
    {
        id: 1,
        type: 'shop',
        name: 'Headlights & Lighting',
        slug: 'headlights-lighting',
        image: '/images/categories/category-1.jpg',
        items: 131,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 2,
        type: 'shop',
        name: 'Turn Signals',
        slug: 'turn-signals',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 3,
        type: 'shop',
        name: 'Fog Lights',
        slug: 'fog-lights',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 4,
        type: 'shop',
        name: 'Headlights',
        slug: 'headlights',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 5,
        type: 'shop',
        name: 'Switches & Relays',
        slug: 'switches-relays',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 6,
        type: 'shop',
        name: 'Tail Lights',
        slug: 'tail-lights',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 7,
        type: 'shop',
        name: 'Corner Lights',
        slug: 'corner-lights',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 8,
        type: 'shop',
        name: 'Off-Road Lighting',
        slug: 'off-road-lighting',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 9,
        type: 'shop',
        name: 'Lighting Accessories',
        slug: 'lighting-accessories',
        image: null,
        items: undefined,
        parent: {
            id: 1,
            type: 'shop',
            name: 'Headlights & Lighting',
            slug: 'headlights-lighting',
            image: '/images/categories/category-1.jpg',
            items: 131,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 10,
        type: 'shop',
        name: 'Fuel System',
        slug: 'fuel-system',
        image: '/images/categories/category-2.jpg',
        items: 356,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 11,
        type: 'shop',
        name: 'Fuel Pumps',
        slug: 'fuel-pumps',
        image: null,
        items: undefined,
        parent: {
            id: 10,
            type: 'shop',
            name: 'Fuel System',
            slug: 'fuel-system',
            image: '/images/categories/category-2.jpg',
            items: 356,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 12,
        type: 'shop',
        name: 'Motor Oil',
        slug: 'motor-oil',
        image: null,
        items: undefined,
        parent: {
            id: 10,
            type: 'shop',
            name: 'Fuel System',
            slug: 'fuel-system',
            image: '/images/categories/category-2.jpg',
            items: 356,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 13,
        type: 'shop',
        name: 'Gas Caps',
        slug: 'gas-caps',
        image: null,
        items: undefined,
        parent: {
            id: 10,
            type: 'shop',
            name: 'Fuel System',
            slug: 'fuel-system',
            image: '/images/categories/category-2.jpg',
            items: 356,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 14,
        type: 'shop',
        name: 'Fuel Injector',
        slug: 'fuel-injector',
        image: null,
        items: undefined,
        parent: {
            id: 10,
            type: 'shop',
            name: 'Fuel System',
            slug: 'fuel-system',
            image: '/images/categories/category-2.jpg',
            items: 356,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 15,
        type: 'shop',
        name: 'Control Motor',
        slug: 'control-motor',
        image: null,
        items: undefined,
        parent: {
            id: 10,
            type: 'shop',
            name: 'Fuel System',
            slug: 'fuel-system',
            image: '/images/categories/category-2.jpg',
            items: 356,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 16,
        type: 'shop',
        name: 'Body Parts',
        slug: 'body-parts',
        image: '/images/categories/category-3.jpg',
        items: 54,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 17,
        type: 'shop',
        name: 'Bumpers',
        slug: 'bumpers',
        image: null,
        items: undefined,
        parent: {
            id: 16,
            type: 'shop',
            name: 'Body Parts',
            slug: 'body-parts',
            image: '/images/categories/category-3.jpg',
            items: 54,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 18,
        type: 'shop',
        name: 'Hoods',
        slug: 'hoods',
        image: null,
        items: undefined,
        parent: {
            id: 16,
            type: 'shop',
            name: 'Body Parts',
            slug: 'body-parts',
            image: '/images/categories/category-3.jpg',
            items: 54,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 19,
        type: 'shop',
        name: 'Grilles',
        slug: 'grilles',
        image: null,
        items: undefined,
        parent: {
            id: 16,
            type: 'shop',
            name: 'Body Parts',
            slug: 'body-parts',
            image: '/images/categories/category-3.jpg',
            items: 54,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 20,
        type: 'shop',
        name: 'Fog Lights',
        slug: 'fog-lights',
        image: null,
        items: undefined,
        parent: {
            id: 16,
            type: 'shop',
            name: 'Body Parts',
            slug: 'body-parts',
            image: '/images/categories/category-3.jpg',
            items: 54,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 21,
        type: 'shop',
        name: 'Door Handles',
        slug: 'door-handles',
        image: null,
        items: undefined,
        parent: {
            id: 16,
            type: 'shop',
            name: 'Body Parts',
            slug: 'body-parts',
            image: '/images/categories/category-3.jpg',
            items: 54,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 22,
        type: 'shop',
        name: 'Interior Parts',
        slug: 'interior-parts',
        image: '/images/categories/category-4.jpg',
        items: 274,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 23,
        type: 'shop',
        name: 'Dashboards',
        slug: 'dashboards',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 24,
        type: 'shop',
        name: 'Seat Covers',
        slug: 'seat-covers',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 25,
        type: 'shop',
        name: 'Floor Mats',
        slug: 'floor-mats',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 26,
        type: 'shop',
        name: 'Sun Shades',
        slug: 'sun-shades',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 27,
        type: 'shop',
        name: 'Visors',
        slug: 'visors',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 28,
        type: 'shop',
        name: 'Car Covers',
        slug: 'car-covers',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 29,
        type: 'shop',
        name: 'Accessories',
        slug: 'interior-parts-accessories',
        image: null,
        items: undefined,
        parent: {
            id: 22,
            type: 'shop',
            name: 'Interior Parts',
            slug: 'interior-parts',
            image: '/images/categories/category-4.jpg',
            items: 274,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 30,
        type: 'shop',
        name: 'Tires & Wheels',
        slug: 'tires-wheels',
        image: '/images/categories/category-5.jpg',
        items: 508,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 31,
        type: 'shop',
        name: 'Wheel Covers',
        slug: 'wheel-covers',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 32,
        type: 'shop',
        name: 'Brake Kits',
        slug: 'brake-kits',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 33,
        type: 'shop',
        name: 'Tire Chains',
        slug: 'tire-chains',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 34,
        type: 'shop',
        name: 'Wheel disks',
        slug: 'wheel-disks',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 35,
        type: 'shop',
        name: 'Tires',
        slug: 'tires',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 36,
        type: 'shop',
        name: 'Sensors',
        slug: 'sensors',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 37,
        type: 'shop',
        name: 'Accessories',
        slug: 'tires-wheels-accessories',
        image: null,
        items: undefined,
        parent: {
            id: 30,
            type: 'shop',
            name: 'Tires & Wheels',
            slug: 'tires-wheels',
            image: '/images/categories/category-5.jpg',
            items: 508,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 38,
        type: 'shop',
        name: 'Engine & Drivetrain',
        slug: 'engine-drivetrain',
        image: '/images/categories/category-6.jpg',
        items: 95,
        parent: null,
        children: [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
        layout: 'products',
        customFields: {},
    },
    {
        id: 39,
        type: 'shop',
        name: 'Timing Belts',
        slug: 'timing-belts',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 40,
        type: 'shop',
        name: 'Spark Plugs',
        slug: 'spark-plugs',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 41,
        type: 'shop',
        name: 'Oil Pans',
        slug: 'oil-pans',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 42,
        type: 'shop',
        name: 'Engine Gaskets',
        slug: 'engine-gaskets',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 43,
        type: 'shop',
        name: 'Oil Filters',
        slug: 'oil-filters',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 44,
        type: 'shop',
        name: 'Engine Mounts',
        slug: 'engine-mounts',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 45,
        type: 'shop',
        name: 'Accessories',
        slug: 'engine-drivetrain-accessories',
        image: null,
        items: undefined,
        parent: {
            id: 38,
            type: 'shop',
            name: 'Engine & Drivetrain',
            slug: 'engine-drivetrain',
            image: '/images/categories/category-6.jpg',
            items: 95,
            parent: null,
            children: [Array],
            layout: 'products',
            customFields: {},
        },
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 46,
        type: 'shop',
        name: 'Oils & Lubricants',
        slug: 'oils-lubricants',
        image: '/images/categories/category-7.jpg',
        items: 179,
        parent: null,
        children: [],
        layout: 'products',
        customFields: {},
    },
    {
        id: 47,
        type: 'shop',
        name: 'Tools & Garage',
        slug: 'tools-garage',
        image: '/images/categories/category-8.jpg',
        items: 106,
        parent: null,
        children: [],
        layout: 'products',
        customFields: {},
    },
];
