import { IShopCategory } from '~/interfaces/category';

export const categoriesData: any = [
    {
        id: 1,
        count: 2,
        type: 'shop',
        name: 'Трансмиссия',
        slug: 'transmissija',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [],
    },
    {
        id: 2,
        count: 13,
        type: 'shop',
        name: 'Двигатель',
        slug: 'dvigatel',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [6, 7, 29, 30, 31, 32, 33, 34, 35],
    },
    {
        id: 6,
        count: 5,
        type: 'shop',
        name: 'Головка',
        slug: 'fuel-system',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [27, 28],
    },
    {
        id: 27,
        count: 4,
        type: 'shop',
        name: 'Распредвал',
        slug: 'raspredval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 6,
        children: [],
    },
    {
        id: 28,
        count: 1,
        type: 'shop',
        name: 'Головка в сборе',
        slug: 'golovka-v-sbore',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 6,
        children: [],
    },
    {
        id: 7,
        count: 5,
        type: 'shop',
        name: 'Поршневая',
        slug: 'porshnevaja',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [8, 9],
    },
    {
        id: 8,
        count: 2,
        type: 'shop',
        name: 'Коленвал',
        slug: 'kolenval',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 7,
        children: [],
    },
    {
        id: 9,
        count: 3,
        type: 'shop',
        name: 'Поршни',
        slug: 'porshni',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 7,
        children: [10],
    },
    {
        id: 10,
        count: 2,
        type: 'shop',
        name: 'Кольца поршневые',
        slug: 'koltsa-porshnevye',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 9,
        children: [],
    },
    {
        id: 29,
        count: 1,
        type: 'shop',
        name: 'Масляный насос',
        slug: 'masljanyj-nasos',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 30,
        count: 0,
        type: 'shop',
        name: 'Генератор',
        slug: 'generator',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [36],
    },
    {
        id: 36,
        count: 0,
        type: 'shop',
        name: 'Электеика Герератора',
        slug: 'elekteika-gereratora',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 30,
        children: [37],
    },
    {
        id: 37,
        count: 0,
        type: 'shop',
        name: 'Проводка',
        slug: 'provodka',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 36,
        children: [],
    },
    {
        id: 31,
        count: 2,
        type: 'shop',
        name: 'Радиатор',
        slug: 'radiator',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 32,
        count: 0,
        type: 'shop',
        name: 'Вискомуфта',
        slug: 'viskomufta',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 33,
        count: 0,
        type: 'shop',
        name: 'Поддон',
        slug: 'poddon',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 34,
        count: 0,
        type: 'shop',
        name: 'Блок цилиндров',
        slug: 'blok-tsilindrov',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 35,
        count: 0,
        type: 'shop',
        name: 'Крышка клапанов',
        slug: 'kryshka-klapanov',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 2,
        children: [],
    },
    {
        id: 3,
        count: 0,
        type: 'shop',
        name: 'Кузов',
        slug: 'kuzov',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [15, 16, 17],
    },
    {
        id: 15,
        count: 0,
        type: 'shop',
        name: 'Капот',
        slug: 'kapot',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 3,
        children: [],
    },
    {
        id: 16,
        count: 0,
        type: 'shop',
        name: 'Крылья',
        slug: 'krylja',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 3,
        children: [],
    },
    {
        id: 17,
        count: 0,
        type: 'shop',
        name: 'Бампреры',
        slug: 'bamprery',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 3,
        children: [18, 19],
    },
    {
        id: 18,
        count: 0,
        type: 'shop',
        name: 'Бампер передний',
        slug: 'bamper-perednij',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 17,
        children: [],
    },
    {
        id: 19,
        count: 0,
        type: 'shop',
        name: 'Бампер Задний',
        slug: 'bamper-zadnij',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 17,
        children: [],
    },
    {
        id: 4,
        count: 5,
        type: 'shop',
        name: 'Автохимия',
        slug: 'avtohimija',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [20],
    },
    {
        id: 20,
        count: 5,
        type: 'shop',
        name: 'Масло',
        slug: 'maslo',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 4,
        children: [21, 22],
    },
    {
        id: 21,
        count: 1,
        type: 'shop',
        name: 'Масло Двигателя',
        slug: 'maslo-dvigatelja',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 20,
        children: [],
    },
    {
        id: 22,
        count: 4,
        type: 'shop',
        name: 'Масло Трансмиссионное',
        slug: 'maslo-transmissionnoe',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 20,
        children: [23, 24],
    },
    {
        id: 23,
        count: 4,
        type: 'shop',
        name: 'Масло в Коробку',
        slug: 'maslo-v-korobku',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 22,
        children: [25, 26],
    },
    {
        id: 25,
        count: 2,
        type: 'shop',
        name: 'Масло в Коробку Автомат',
        slug: 'maslo-v-korobku-avtomat',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 23,
        children: [],
    },
    {
        id: 26,
        count: 2,
        type: 'shop',
        name: 'Масло в Коробку Механика',
        slug: 'maslo-v-korobku-mehanika',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 23,
        children: [],
    },
    {
        id: 24,
        count: 0,
        type: 'shop',
        name: 'Масло в Редуктор',
        slug: 'maslo-v-reduktor',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 22,
        children: [],
    },
    {
        id: 5,
        count: 1,
        type: 'shop',
        name: 'Инструменты',
        slug: 'instrumenty',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: null,
        children: [11, 13],
    },
    {
        id: 11,
        count: 0,
        type: 'shop',
        name: 'Ключи Гаечные',
        slug: 'kljuchi-gaechnye',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 5,
        children: [12],
    },
    {
        id: 12,
        count: 0,
        type: 'shop',
        name: 'Ключи рожковые',
        slug: 'kljuchi-rozhkovye',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 11,
        children: [],
    },
    {
        id: 13,
        count: 1,
        type: 'shop',
        name: 'Наборы инструментов',
        slug: 'nabory-instrumentov',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 5,
        children: [14],
    },
    {
        id: 14,
        count: 0,
        type: 'shop',
        name: 'Наборы отверток',
        slug: 'nabory-otvertok',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        layout: 'products',
        parent: 13,
        children: [],
    },
];

export const dataRecursive: any = [
    {
        parent: null,
        layout: 'products',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        slug: 'transmissija',
        name: 'Трансмиссия',
        type: 'shop',
        count: 2,
        id: 1,
    },
    {
        children: [
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'raspredval',
                        name: 'Распредвал',
                        type: 'shop',
                        count: 4,
                        id: 27,
                    },
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'golovka-v-sbore',
                        name: 'Головка в сборе',
                        type: 'shop',
                        count: 1,
                        id: 28,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'fuel-system',
                name: 'Головка',
                type: 'shop',
                count: 5,
                id: 6,
            },
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'kolenval',
                        name: 'Коленвал',
                        type: 'shop',
                        count: 2,
                        id: 8,
                    },
                    {
                        children: [
                            {
                                parent: '[Circular]',
                                layout: 'products',
                                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                slug: 'koltsa-porshnevye',
                                name: 'Кольца поршневые',
                                type: 'shop',
                                count: 2,
                                id: 10,
                            },
                        ],
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'porshni',
                        name: 'Поршни',
                        type: 'shop',
                        count: 3,
                        id: 9,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'porshnevaja',
                name: 'Поршневая',
                type: 'shop',
                count: 5,
                id: 7,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'masljanyj-nasos',
                name: 'Масляный насос',
                type: 'shop',
                count: 1,
                id: 29,
            },
            {
                children: [
                    {
                        children: [
                            {
                                parent: '[Circular]',
                                layout: 'products',
                                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                slug: 'provodka',
                                name: 'Проводка',
                                type: 'shop',
                                count: 0,
                                id: 37,
                            },
                        ],
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'elekteika-gereratora',
                        name: 'Электеика Герератора',
                        type: 'shop',
                        count: 0,
                        id: 36,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'generator',
                name: 'Генератор',
                type: 'shop',
                count: 1,
                id: 30,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'radiator',
                name: 'Радиатор',
                type: 'shop',
                count: 2,
                id: 31,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'viskomufta',
                name: 'Вискомуфта',
                type: 'shop',
                count: 0,
                id: 32,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'poddon',
                name: 'Поддон',
                type: 'shop',
                count: 0,
                id: 33,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'blok-tsilindrov',
                name: 'Блок цилиндров',
                type: 'shop',
                count: 0,
                id: 34,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'kryshka-klapanov',
                name: 'Крышка клапанов',
                type: 'shop',
                count: 0,
                id: 35,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'kreplenie-dvigatelja',
                name: 'Крепление двигателя',
                type: 'shop',
                count: 0,
                id: 38,
            },
        ],
        parent: null,
        layout: 'products',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        slug: 'dvigatel',
        name: 'Двигатель',
        type: 'shop',
        count: 14,
        id: 2,
    },
    {
        children: [
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'kapot',
                name: 'Капот',
                type: 'shop',
                count: 0,
                id: 15,
            },
            {
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'krylja',
                name: 'Крылья',
                type: 'shop',
                count: 0,
                id: 16,
            },
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'bamper-perednij',
                        name: 'Бампер передний',
                        type: 'shop',
                        count: 0,
                        id: 18,
                    },
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'bamper-zadnij',
                        name: 'Бампер Задний',
                        type: 'shop',
                        count: 0,
                        id: 19,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'bamprery',
                name: 'Бампреры',
                type: 'shop',
                count: 0,
                id: 17,
            },
        ],
        parent: null,
        layout: 'products',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        slug: 'kuzov',
        name: 'Кузов',
        type: 'shop',
        count: 0,
        id: 3,
    },
    {
        children: [
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'maslo-dvigatelja',
                        name: 'Масло Двигателя',
                        type: 'shop',
                        count: 1,
                        id: 21,
                    },
                    {
                        children: [
                            {
                                children: [
                                    {
                                        parent: '[Circular]',
                                        layout: 'products',
                                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                        slug: 'maslo-v-korobku-avtomat',
                                        name: 'Масло в Коробку Автомат',
                                        type: 'shop',
                                        count: 2,
                                        id: 25,
                                    },
                                    {
                                        parent: '[Circular]',
                                        layout: 'products',
                                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                        slug: 'maslo-v-korobku-mehanika',
                                        name: 'Масло в Коробку Механика',
                                        type: 'shop',
                                        count: 2,
                                        id: 26,
                                    },
                                ],
                                parent: '[Circular]',
                                layout: 'products',
                                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                slug: 'maslo-v-korobku',
                                name: 'Масло в Коробку',
                                type: 'shop',
                                count: 4,
                                id: 23,
                            },
                            {
                                parent: '[Circular]',
                                layout: 'products',
                                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                                slug: 'maslo-v-reduktor',
                                name: 'Масло в Редуктор',
                                type: 'shop',
                                count: 0,
                                id: 24,
                            },
                        ],
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'maslo-transmissionnoe',
                        name: 'Масло Трансмиссионное',
                        type: 'shop',
                        count: 4,
                        id: 22,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'maslo',
                name: 'Масло',
                type: 'shop',
                count: 5,
                id: 20,
            },
        ],
        parent: null,
        layout: 'products',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        slug: 'avtohimija',
        name: 'Автохимия',
        type: 'shop',
        count: 5,
        id: 4,
    },
    {
        children: [
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'kljuchi-rozhkovye',
                        name: 'Ключи рожковые',
                        type: 'shop',
                        count: 0,
                        id: 12,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'kljuchi-gaechnye',
                name: 'Ключи Гаечные',
                type: 'shop',
                count: 0,
                id: 11,
            },
            {
                children: [
                    {
                        parent: '[Circular]',
                        layout: 'products',
                        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                        slug: 'nabory-otvertok',
                        name: 'Наборы отверток',
                        type: 'shop',
                        count: 0,
                        id: 14,
                    },
                ],
                parent: '[Circular]',
                layout: 'products',
                image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
                slug: 'nabory-instrumentov',
                name: 'Наборы инструментов',
                type: 'shop',
                count: 1,
                id: 13,
            },
        ],
        parent: null,
        layout: 'products',
        image: 'http://localhost:8000/media/123/555_tf/IMG_4210.jpg',
        slug: 'instrumenty',
        name: 'Инструменты',
        type: 'shop',
        count: 1,
        id: 5,
    },
];
